### ISSUE TITLE
Management API error if we send invalid UID in withdraws/new

### ISSUE THREAD

**Issue by ysv** [openware/peatio#1272]
```ruby
    86:     end
    87:     post '/withdraws/new' do
    88:       currency = Currency.find(params[:currency])
    89:       member   = Authentication.find_by(provider: :barong, uid: params[:uid])&.member
    90:       binding.pry
 => 91:       withdraw = "withdraws/#{currency.type}".camelize.constantize.new \
    92:         sum:            params[:amount],
    93:         member:         member,
    94:         currency:       currency,
    95:         tid:            params[:tid],
    96:         rid:            params[:rid]

[1] pry(#<#<Class:0x0000561888b55eb8>>)> 
   (0.2ms)  BEGIN
   (0.5ms)  SELECT COUNT(*) FROM `withdraws` WHERE `withdraws`.`type` IN ('Withdraws::Coin') AND `withdraws`.`tid` = 'TID1243357A5D'
   (0.2ms)  ROLLBACK
  Parameters: {"uid"=>"ysavchuk@heliostech.fr", "rid"=>"12345", "currency"=>"btc", "amount"=>10}
Completed 500 Internal Server Error in 11932.27ms (Views: 11930.03ms | DB: 2.24ms)


NoMethodError (undefined method `ac' for nil:NilClass):
  app/models/withdraw.rb:20:in `block in <class:Withdraw>'
  app/api/management_api_v1/withdraws.rb:98:in `block in <class:Withdraws>'
```

**Comment by yivo** [comment]
1.6 & 1.7 are not affected. Fixed in #1299.
