### ISSUE TITLE
ETH and ERC20 dont reflect to user account

### ISSUE THREAD

**Issue by greo2017** [openware/peatio#1505]
Hello,

ETH deposit and ERC20 deposit dont reflect to users balance. I try to use following code but it gies error.

> code=eth bundle exec rake coin:sync_deposit

```
rake aborted!
CoinRPC::JSONRPCError: {"code"=>-32601, "message"=>"The method listtransactions_ does not exist/is not available"}
/home/deploy/peatio/current/app/services/coin_rpc.rb:34:in `handle'
/home/deploy/peatio/current/app/services/coin_rpc.rb:23:in `method_missing'
/home/deploy/peatio/current/lib/tasks/coin.rake:15:in `block (2 levels) in <top (required)>'
/home/deploy/.rbenv/versions/2.2.2/bin/bundle:23:in `load'
/home/deploy/.rbenv/versions/2.2.2/bin/bundle:23:in `<main>'
Tasks: TOP => coin:sync_deposit
(See full trace by running task with --trace)
```

**Comment by ysv** [comment]
@greo2017 which version did you use ?
We don't have this task now
