### ISSUE TITLE
Error on withdraw audit: Withdraw#blockchain_api delegated to currency.blockchain_api, but currency is nil

### ISSUE THREAD

**Issue by ysv** [openware/peatio#1560]

**Comment by ysv** [comment]
```
Error on withdraw audit: Withdraw#blockchain_api delegated to currency.blockchain_api, but currency is nil: #<Withdraws::Coin id: 1, account_id: 9, member_id: 3, currency_id: 0, amount: 0.13e1, fee: 0.0, created_at: "2018-08-21 14:57:26", updated_at: "2018-08-21 14:57:26", txid: nil, aasm_state: "accepted", sum: 0.13e1, type: "Withdraws::Coin", tid: "TIDEE0020DD5B", rid: "2NFubshehwFdMJospvq2zXSyu8FuLkubaxR">
/home/app/app/models/concerns/belongs_to_currency.rb:19:in `rescue in blockchain_api'
/home/app/app/models/concerns/belongs_to_currency.rb:19:in `blockchain_api'
```

*currency_id: 0*

**Comment by ysv** [comment]
Issue was caused because of problems with migrations
