### ISSUE TITLE
issue with set_gon

### ISSUE THREAD

**Issue by surfy1h** [openware/peatio#1624]
error running server: 

NoMethodError (undefined method `attributes' for nil:NilClass):
  app/controllers/application_controller.rb:50:in `set_gon'

I have tried to roll back to gon to version 5.2.0

 **bundle info gon**
  * gon (5.2.0)
        Summary: Get your Rails variables in your JS
        Homepage: https://github.com/gazay/gon
        Path: /home/deploy/.rvm/gems/ruby-2.5.1/gems/gon-5.2.0

I think this error is due to seeding of the sql database not working 

**~/code/peatio$ rake seed:wallets**
   (0.1ms)  BEGIN
  Wallet Exists (0.3ms)  SELECT  1 AS one FROM `wallets` WHERE `wallets`.`name` = 'Ethereum Deposit Wallet' LIMIT 1
  Currency Load (0.3ms)  SELECT  `currencies`.* FROM `currencies` WHERE `currencies`.`id` = 0 LIMIT 1
  Wallet Exists (0.4ms)  SELECT  1 AS one FROM `wallets` WHERE `wallets`.`name` = BINARY 'Ethereum Deposit Wallet' LIMIT 1
   (0.1ms)  ROLLBACK
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Currency can't be blank
/home/deploy/.rvm/gems/ruby-2.5.1/gems/activerecord-4.2.10/lib/active_record/validations.rb:79:in `raise_record_invalid'

**Comment by ysv** [comment]
@surfy1h run `rake db:seed` to setup db

**Comment by rraallvv** [comment]
I'm seeing the same issue, when I try `bundle exec rake db:seed` I get this:

```
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Bid unit is not enabled.
/home/deploy/.rvm/gems/ruby-2.5.0/gems/activerecord-4.2.10/lib/active_record/validations.rb:79:in `raise_record_invalid'
/home/deploy/.rvm/gems/ruby-2.5.0/gems/activerecord-4.2.10/lib/active_record/validations.rb:43:in `save!'
/home/deploy/.rvm/gems/ruby-2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/home/deploy/.rvm/gems/ruby-2.5.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:291:in `block in save!'
/home/deploy/.rvm/gems/ruby-2.5.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/home/deploy/.rvm/gems/ruby-2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
/home/deploy/.rvm/gems/ruby-2.5.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:220:in `transaction'
/home/deploy/.rvm/gems/ruby-2.5.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/home/deploy/.rvm/gems/ruby-2.5.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:291:in `save!'
/home/deploy/.rvm/gems/ruby-2.5.0/gems/scout_apm-2.4.11/lib/scout_apm/instruments/active_record.rb:375:in `save!'
/home/deploy/.rvm/gems/ruby-2.5.0/gems/activerecord-4.2.10/lib/active_record/persistence.rb:51:in `create!'
/home/deploy/peatio/lib/tasks/markets.rake:10:in `block (4 levels) in <top (required)>'
/home/deploy/peatio/lib/tasks/markets.rake:8:in `each'
/home/deploy/peatio/lib/tasks/markets.rake:8:in `block (3 levels) in <top (required)>'
/home/deploy/.rvm/gems/ruby-2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/deploy/.rvm/gems/ruby-2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/home/deploy/.rvm/gems/ruby-2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/deploy/.rvm/gems/ruby-2.5.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:220:in `transaction'
/home/deploy/peatio/lib/tasks/markets.rake:7:in `block (2 levels) in <top (required)>'
/home/deploy/peatio/db/seeds.rb:5:in `<top (required)>'
/home/deploy/.rvm/gems/ruby-2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/home/deploy/.rvm/gems/ruby-2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
/home/deploy/.rvm/gems/ruby-2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/deploy/.rvm/gems/ruby-2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/home/deploy/.rvm/gems/ruby-2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:547:in `load_seed'
/home/deploy/.rvm/gems/ruby-2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:253:in `load_seed'
/home/deploy/.rvm/gems/ruby-2.5.0/gems/activerecord-4.2.10/lib/active_record/railties/databases.rake:173:in `block (2 levels) in <top (required)>'
/home/deploy/.rvm/gems/ruby-2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/deploy/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `eval'
/home/deploy/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => markets:seed
(See full trace by running task with --trace)
```
