### ISSUE TITLE
bundle exec rake currencies:seed & markets:seed [rake aborted!]

### ISSUE THREAD

**Issue by knkrth** [openware/peatio#1659]
Hi, Can anyone help?

```
code/peatio$ bundle exec rake currencies:seed --trace
rake aborted!
Don't know how to build task 'currencies:seed' (see --tasks)
/home/kartx/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/task_manager.rb:59:in `[]'
/home/kartx/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:159:in `invoke_task'
/home/kartx/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/kartx/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/home/kartx/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/home/kartx/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/home/kartx/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/home/kartx/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
/home/kartx/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/home/kartx/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/home/kartx/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/kartx/.rvm/gems/ruby-2.5.1/bin/rake:23:in `load'
/home/kartx/.rvm/gems/ruby-2.5.1/bin/rake:23:in `<main>'
/home/kartx/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
/home/kartx/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by knkrth** [comment]
```
code/peatio$ bundle exec rake markets:seed --trace
rake aborted!
Don't know how to build task 'markets:seed' (see --tasks)
/home/kartx/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/task_manager.rb:59:in `[]'
/home/kartx/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:159:in `invoke_task'
/home/kartx/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/kartx/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/home/kartx/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/home/kartx/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/home/kartx/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/home/kartx/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
/home/kartx/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/home/kartx/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/home/kartx/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/kartx/.rvm/gems/ruby-2.5.1/bin/rake:23:in `load'
/home/kartx/.rvm/gems/ruby-2.5.1/bin/rake:23:in `<main>'
/home/kartx/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
/home/kartx/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by ghost** [comment]
rake db:seed

**Comment by ysv** [comment]
@laugh26 Thanks!
