### ISSUE TITLE
workbench database currencies:seed issue 

### ISSUE THREAD

**Issue by knkrth** [openware/peatio#1675]
`Make build` run without any error & `Make run` failed.

```
platform: ubuntu 16.04
docker: 18.06.1-ce
docker compose: 1.22.0

workbench from master branch, follow the README steps and make run failed:

make build
make bitcoin
make run

... ...

   (0.1ms)  SHOW CREATE TABLE `orders`
Model files unchanged.
  ActiveRecord::SchemaMigration Load (0.7ms)  SELECT `schema_migrations`.* FROM `schema_migrations`
   (0.2ms)  BEGIN
  Currency Exists (58.0ms)  SELECT  1 AS one FROM `currencies` WHERE `currencies`.`id` = 'usd' LIMIT 1
  Currency Exists (139.8ms)  SELECT  1 AS one FROM `currencies` WHERE `currencies`.`id` = BINARY 'usd' LIMIT 1
  SQL (0.3ms)  INSERT INTO `currencies` (`options`, `id`, `symbol`, `type`, `quick_withdraw_limit`, `created_at`, `updated_at`) VALUES ('{\"bitgo_wallet_address\":null,\"erc20_contract_address\":null}', 'usd', '$', 'fiat', 1000.0, '2018-08-30 06:41:57', '2018-08-30 06:41:57')
  Member Load (0.2ms)  SELECT  `members`.* FROM `members`  ORDER BY `members`.`id` ASC LIMIT 1000
  Currency Exists (0.2ms)  SELECT  1 AS one FROM `currencies` WHERE `currencies`.`id` = 'eth' LIMIT 1
   (58.8ms)  ROLLBACK
rake aborted!
ActiveRecord::UnknownAttributeError: unknown attribute 'blockchain_key' for Currency.
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:59:in `rescue in _assign_attribute'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:53:in `_assign_attribute'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:35:in `each'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/core.rb:566:in `init_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/core.rb:281:in `initialize'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/inheritance.rb:61:in `new'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/inheritance.rb:61:in `new'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/persistence.rb:50:in `create!'
/home/app/lib/tasks/currencies.rake:11:in `block (4 levels) in <top (required)>'
/home/app/lib/tasks/currencies.rake:9:in `each'
/home/app/lib/tasks/currencies.rake:9:in `block (3 levels) in <top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:220:in `transaction'
/home/app/lib/tasks/currencies.rake:8:in `block (2 levels) in <top (required)>'
/home/app/db/seeds.rb:4:in `<top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:547:in `load_seed'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:253:in `load_seed'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/railties/databases.rake:173:in `block (2 levels) in <top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/bundle:104:in `load'
/usr/local/bundle/bin/bundle:104:in `<main>'

Caused by:
NoMethodError: undefined method `blockchain_key=' for #<Currency:0x0000562de29fb670>
/opt/vendor/bundle/ruby/2.5.0/gems/activemodel-4.2.10/lib/active_model/attribute_methods.rb:433:in `method_missing'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:54:in `public_send'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:35:in `each'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/core.rb:566:in `init_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/core.rb:281:in `initialize'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/inheritance.rb:61:in `new'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/inheritance.rb:61:in `new'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/persistence.rb:50:in `create!'
/home/app/lib/tasks/currencies.rake:11:in `block (4 levels) in <top (required)>'
/home/app/lib/tasks/currencies.rake:9:in `each'
/home/app/lib/tasks/currencies.rake:9:in `block (3 levels) in <top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:220:in `transaction'
/home/app/lib/tasks/currencies.rake:8:in `block (2 levels) in <top (required)>'
/home/app/db/seeds.rb:4:in `<top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:547:in `load_seed'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:253:in `load_seed'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/railties/databases.rake:173:in `block (2 levels) in <top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/bundle:104:in `load'
/usr/local/bundle/bin/bundle:104:in `<main>'
Tasks: TOP => currencies:seed
(See full trace by running task with --trace)
Makefile:42: recipe for target 'setup-apps' failed
make: *** [setup-apps] Error 1
```

**Comment by ysv** [comment]
@knkrth https://github.com/rubykube/workbench/issues/144

**Comment by knkrth** [comment]
@ysv [https://github.com/rubykube/workbench/issues/144](rubykube/workbench#144) no one response there so that only I created a issue here. Do you know how to fix it?

**Comment by ysv** [comment]
@knkrth Please try the following:

Cleanup app directory
```
$> rm -rf app/*
```
Update submodules
```
$> make update
```

**Comment by knkrth** [comment]
@ysv I did that still no luck. Same error :(

**Comment by ysv** [comment]
@knkrth try `docker-compose volume prune -f`

**Comment by ysv** [comment]
@knkrth did it help you ?

**Comment by knkrth** [comment]
After the recent update on https://github.com/rubykube/workbench everything works fine :)
