### ISSUE TITLE
Trading UI Routing Issue

### ISSUE THREAD

**Issue by Michailaros** [openware/peatio#1816]
Hi. I am trying to configure peatio-trading-ui on localhost. I have peatio working on localhost:3000 but when i run the trading-ui on localhost:4000 after following the instructions i am met with this error. 

![routingissue](https://user-images.githubusercontent.com/45218014/48812028-5c018380-ed80-11e8-8410-bdcec26d5691.JPG)

I have looked around and seen references to host off of a domain. But am unsure how to do this. Could anyone point me in the right direction of how to get it hooked up to a domain name.

Thank you in advance.

**Comment by openbooknoobdeveloper** [comment]
have you checked it?

https://github.com/rubykube/workbench/wiki

**Comment by dragon28** [comment]
I am having the same problem 

https://github.com/rubykube/peatio-trading-ui/issues/111

**Comment by ysv** [comment]
@Michailaros @dragon28 You need to have peatio and peatio-trading-ui on the same host and port 
Please use workbench to run peatio and peatio-trading-ui

**Comment by dragon28** [comment]
> @Michailaros @dragon28 You need to have peatio and peatio-trading-ui on the same host and port
> Please use workbench to run peatio and peatio-trading-ui

@ysv  I tried to run peatio trading ui at same host and same port which was port 3000 by using "bundle exec rails server -p 3000"

and it gave me the following result:

```
~/peatio-trading-ui$ bundle exec rails server -p 3000
WARNING: Use strings for Figaro configuration. false was converted to "false".
=> Booting Puma
=> Rails 5.1.6 application starting in development 
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.11.3 (ruby 2.5.3-p105), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3000
Exiting
Traceback (most recent call last):
	25: from bin/rails:4:in `<main>'
	24: from bin/rails:4:in `require'
	23: from /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/commands.rb:16:in `<top (required)>'
	22: from /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/command.rb:44:in `invoke'
	21: from /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/command/base.rb:63:in `perform'
	20: from /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	19: from /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	18: from /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	17: from /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:130:in `perform'
	16: from /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:130:in `tap'
	15: from /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:135:in `block in perform'
	14: from /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:44:in `start'
	13: from /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/server.rb:297:in `start'
	12: from /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.11.3/lib/rack/handler/puma.rb:69:in `run'
	11: from /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.11.3/lib/puma/launcher.rb:183:in `run'
	10: from /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.11.3/lib/puma/single.rb:87:in `run'
	 9: from /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.11.3/lib/puma/runner.rb:144:in `load_and_bind'
	 8: from /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.11.3/lib/puma/binder.rb:88:in `parse'
	 7: from /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.11.3/lib/puma/binder.rb:88:in `each'
	 6: from /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.11.3/lib/puma/binder.rb:105:in `block in parse'
	 5: from /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.11.3/lib/puma/binder.rb:263:in `add_tcp_listener'
	 4: from /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.11.3/lib/puma/binder.rb:263:in `each'
	 3: from /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.11.3/lib/puma/binder.rb:264:in `block in add_tcp_listener'
	 2: from /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.11.3/lib/puma/binder.rb:270:in `add_tcp_listener'
	 1: from /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.11.3/lib/puma/binder.rb:270:in `new'
/home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.11.3/lib/puma/binder.rb:270:in `initialize': Address already in use - bind(2) for "127.0.0.1" port 3000 (Errno::EADDRINUSE)

```

It said port 3000 already being bind or in use.

**Comment by huuhait** [comment]
run to other port

**Comment by dragon28** [comment]
> run to other port

@Thedabest 

It gave the same routing error which the url was not found.

**Comment by hardywu** [comment]
nginx or traefik issue

**Comment by ramror3** [comment]
@Michailaros 
Hi, Check your application.yml file in Trading-UI. In the application.yml file, there are two hosts. You need to set those hosts properly. Like.
PLATFORM_ROOT_URL: http://localhost:3000  (It is peatio host).
FRONTEND_ROOT_URL: http://localhost:4000 (it is the trading-UI host). Then run it will be work.

**Comment by rastislavcore** [comment]
For me cannot fix issue. Still same

**Comment by ramror3** [comment]
I have fixed that issue.

**Comment by rastislavcore** [comment]
Please share solution. If you don't mind.

In meanwhile I found out, that route ending in "Black hole" and it is necessary install trading frontend. Not sure how the routes are managed between versions in this projects.
Which distribution you are using?

**Comment by mnaichuk** [comment]
peatio-trading-ui is deprecated.
