### ISSUE TITLE
Redis::CommandError (NOAUTH Authentication required.)

### ISSUE THREAD

**Issue by dragon28** [openware/peatio#1823]
Hello People :)

Error Log:

```
~/peatio$ bundle exec rails server -p 3000
/home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. false was converted to "false". (StructuredWarnings::StandardWarning)=> Booting Puma
=> Rails 4.2.10 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Puma starting in single mode...
* Version 3.11.4 (ruby 2.5.3-p105), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3000
Use Ctrl-C to stop


Started GET "/" for 127.0.0.1 at 2018-11-21 18:51:41 +0800
  ActiveRecord::SchemaMigration Load (0.5ms)  SELECT `schema_migrations`.* FROM `schema_migrations`
Processing by WelcomeController#index as HTML
  Market Load (5.1ms)  SELECT  `markets`.* FROM `markets` WHERE `markets`.`enabled` = 1  ORDER BY `markets`.`position` ASC LIMIT 1
Completed 500 Internal Server Error in 116ms (ActiveRecord: 24.5ms)

Redis::CommandError (NOAUTH Authentication required.):
  app/trading/global.rb:45:in `ticker'
  app/models/market.rb:88:in `ticker'
  app/controllers/application_controller.rb:51:in `set_gon'


  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_source.erb (19.8ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (7.8ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.1ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (72.3ms)


Started GET "/" for 127.0.0.1 at 2018-11-21 18:51:47 +0800
Processing by WelcomeController#index as HTML
  Market Load (0.9ms)  SELECT  `markets`.* FROM `markets` WHERE `markets`.`enabled` = 1  ORDER BY `markets`.`position` ASC LIMIT 1
Completed 500 Internal Server Error in 3ms (ActiveRecord: 0.9ms)

Redis::CommandError (NOAUTH Authentication required.):
  app/trading/global.rb:45:in `ticker'
  app/models/market.rb:88:in `ticker'
  app/controllers/application_controller.rb:51:in `set_gon'


  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_source.erb (5.9ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (3.5ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.0ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (28.2ms)


Started GET "/" for 127.0.0.1 at 2018-11-21 18:56:39 +0800
Processing by WelcomeController#index as HTML
  Market Load (8.1ms)  SELECT  `markets`.* FROM `markets` WHERE `markets`.`enabled` = 1  ORDER BY `markets`.`position` ASC LIMIT 1
Completed 500 Internal Server Error in 25ms (ActiveRecord: 8.1ms)

Redis::CommandError (NOAUTH Authentication required.):
  app/trading/global.rb:45:in `ticker'
  app/models/market.rb:88:in `ticker'
  app/controllers/application_controller.rb:51:in `set_gon'


  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_source.erb (5.4ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (13.3ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.9ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (100.2ms)


Started GET "/" for 127.0.0.1 at 2018-11-21 18:56:42 +0800
Processing by WelcomeController#index as HTML
  Market Load (7.1ms)  SELECT  `markets`.* FROM `markets` WHERE `markets`.`enabled` = 1  ORDER BY `markets`.`position` ASC LIMIT 1
Completed 500 Internal Server Error in 12ms (ActiveRecord: 7.1ms)

Redis::CommandError (NOAUTH Authentication required.):
  app/trading/global.rb:45:in `ticker'
  app/models/market.rb:88:in `ticker'
  app/controllers/application_controller.rb:51:in `set_gon'


  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_source.erb (12.4ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.1ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.9ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (71.7ms)


Started GET "/" for 127.0.0.1 at 2018-11-21 18:56:51 +0800
Processing by WelcomeController#index as HTML
  Market Load (8.4ms)  SELECT  `markets`.* FROM `markets` WHERE `markets`.`enabled` = 1  ORDER BY `markets`.`position` ASC LIMIT 1
Completed 500 Internal Server Error in 13ms (ActiveRecord: 8.4ms)

Redis::CommandError (NOAUTH Authentication required.):
  app/trading/global.rb:45:in `ticker'
  app/models/market.rb:88:in `ticker'
  app/controllers/application_controller.rb:51:in `set_gon'


  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_source.erb (40.0ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (14.6ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.1ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (107.6ms)


Started GET "/" for 127.0.0.1 at 2018-11-21 18:57:05 +0800
Processing by WelcomeController#index as HTML
  Market Load (0.6ms)  SELECT  `markets`.* FROM `markets` WHERE `markets`.`enabled` = 1  ORDER BY `markets`.`position` ASC LIMIT 1
Completed 500 Internal Server Error in 9ms (ActiveRecord: 0.6ms)

Redis::CommandError (NOAUTH Authentication required.):
  app/trading/global.rb:45:in `ticker'
  app/models/market.rb:88:in `ticker'
  app/controllers/application_controller.rb:51:in `set_gon'


  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_source.erb (5.3ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.5ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.0ms)
  Rendered /home/dragon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-4.2.10/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (27.2ms)
^C- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2018-11-21 18:57:46 ===
- Goodbye!
Exiting
```
application.yml

```
~/peatio$ cat config/application.yml | grep REDIS

  #REDIS_URL:      redis://localhost:6379
  REDIS_URL:      redis://127.0.0.1:6379
  REDIS_PASSWORD:	qeEx
  #REDIS_PASSWORD: ~ # By default no password is sent to Redis server. Change this if you want to connect using password.

```
Trace:

```
redis (4.0.2) lib/redis/client.rb:119:in `call'
redis (4.0.2) lib/redis.rb:899:in `block in get'
redis (4.0.2) lib/redis.rb:45:in `block in synchronize'
/home/dragon/.rbenv/versions/2.5.3/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
redis (4.0.2) lib/redis.rb:45:in `synchronize'
redis (4.0.2) lib/redis.rb:898:in `get'
redis-store (1.6.0) lib/redis/store/interface.rb:5:in `get'
redis-store (1.6.0) lib/redis/store/serialization.rb:17:in `get'
redis-store (1.6.0) lib/redis/store/namespace.rb:23:in `block in get'
redis-store (1.6.0) lib/redis/store/namespace.rb:89:in `namespace'
redis-store (1.6.0) lib/redis/store/namespace.rb:23:in `get'
redis-activesupport (5.0.7) lib/active_support/cache/redis_store.rb:266:in `block in read_entry'
redis-activesupport (5.0.7) lib/active_support/cache/redis_store.rb:248:in `with'
redis-activesupport (5.0.7) lib/active_support/cache/redis_store.rb:266:in `read_entry'
activesupport (4.2.10) lib/active_support/cache.rb:315:in `block in read'
activesupport (4.2.10) lib/active_support/cache.rb:547:in `block in instrument'
activesupport (4.2.10) lib/active_support/notifications.rb:166:in `instrument'
activesupport (4.2.10) lib/active_support/cache.rb:547:in `instrument'
activesupport (4.2.10) lib/active_support/cache.rb:314:in `read'
app/trading/global.rb:45:in `ticker'
app/models/market.rb:88:in `ticker'
app/controllers/application_controller.rb:51:in `set_gon'
activesupport (4.2.10) lib/active_support/callbacks.rb:432:in `block in make_lambda'
activesupport (4.2.10) lib/active_support/callbacks.rb:164:in `block in halting'
activesupport (4.2.10) lib/active_support/callbacks.rb:504:in `block in call'
activesupport (4.2.10) lib/active_support/callbacks.rb:504:in `each'
activesupport (4.2.10) lib/active_support/callbacks.rb:504:in `call'
activesupport (4.2.10) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
activesupport (4.2.10) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
activesupport (4.2.10) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.10) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.10) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.10) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.10) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.10) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.10) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.10) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.10) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.10) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.10) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.10) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.10) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.10) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.10) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.10) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
actionpack (4.2.10) lib/action_dispatch/routing/route_set.rb:43:in `serve'
actionpack (4.2.10) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.10) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.10) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.10) lib/action_dispatch/routing/route_set.rb:817:in `call'
omniauth (1.8.1) lib/omniauth/strategy.rb:190:in `call!'
omniauth (1.8.1) lib/omniauth/strategy.rb:168:in `call'
omniauth (1.8.1) lib/omniauth/builder.rb:63:in `call'
bullet (5.7.6) lib/bullet/rack.rb:12:in `call'
rack (1.6.11) lib/rack/etag.rb:24:in `call'
rack (1.6.11) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.11) lib/rack/head.rb:13:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.11) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.11) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.10) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.10) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
activerecord (4.2.10) lib/active_record/migration.rb:377:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.10) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
activesupport (4.2.10) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
activesupport (4.2.10) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.10) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.10) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.10) lib/rails/rack/logger.rb:22:in `call'
quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.11) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.11) lib/rack/runtime.rb:18:in `call'
rack (1.6.11) lib/rack/lock.rb:17:in `call'
actionpack (4.2.10) lib/action_dispatch/middleware/static.rb:120:in `call'
rack (1.6.11) lib/rack/sendfile.rb:113:in `call'
railties (4.2.10) lib/rails/engine.rb:518:in `call'
railties (4.2.10) lib/rails/application.rb:165:in `call'
rack (1.6.11) lib/rack/content_length.rb:15:in `call'
puma (3.11.4) lib/puma/configuration.rb:225:in `call'
puma (3.11.4) lib/puma/server.rb:632:in `handle_request'
puma (3.11.4) lib/puma/server.rb:446:in `process_client'
puma (3.11.4) lib/puma/server.rb:306:in `block in run'
puma (3.11.4) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

gem packages:

```
aasm (5.0.1)
actioncable (5.2.1, 5.1.6)
actionmailer (5.2.1, 5.1.6, 4.2.10)
actionpack (5.2.1, 5.1.6, 4.2.10)
actionview (5.2.1, 5.1.6, 4.2.10)
activejob (5.2.1, 5.1.6, 4.2.10)
activemodel (5.2.1, 5.1.6, 4.2.10)
activerecord (5.2.1, 5.1.6, 4.2.10)
activestorage (5.2.1)
activesupport (5.2.1, 5.1.6, 4.2.10)
addressable (2.5.2)
amq-protocol (2.3.0)
amqp (1.8.0)
angularjs-rails (1.3.15)
annotate (2.7.4)
arel (9.0.0, 8.0.0, 6.0.4)
arel-is-blank (1.0.0)
arel-to-sql (1.0.0)
ast (2.4.0)
autoprefixer-rails (9.3.1)
aws-sigv4 (1.0.3)
axiom-types (0.1.1)
base58 (0.2.3)
bcrypt (3.1.12)
bigdecimal (default: 1.3.4)
bindex (0.5.0)
bootsnap (1.3.2)
bootstrap (4.1.3)
bootstrap-sass (3.2.0.2)
bourbon (4.3.4)
browser (2.5.3)
builder (3.2.3)
bullet (5.7.6)
bundler (1.17.1, default: 1.16.6)
bunny (2.12.0, 2.11.0)
byebug (10.0.2)
cancancan (2.2.0)
capybara (3.11.1)
carrierwave (1.2.3)
cash-addr (0.1.1)
clamp (1.3.0)
clipboard-rails (1.7.1)
cmath (default: 1.0.0)
coderay (1.1.2)
coercible (1.0.0)
coffee-rails (4.2.2)
coffee-script (2.4.1)
coffee-script-source (1.12.2)
concurrent-ruby (1.1.3, 1.0.5)
countries (2.1.4)
crack (0.4.3)
crass (1.0.4, 1.0.3)
csv (default: 1.0.0)
database_cleaner (1.7.0)
date (default: 1.0.0)
descendants_tracker (0.0.4)
did_you_mean (1.2.0)
diff-lcs (1.3)
digest-sha3 (1.1.0)
easy_table (0.0.10)
ejs (1.1.1)
em-websocket (0.5.1)
email_validator (1.6.0)
enumerize (2.2.2)
equalizer (0.0.11)
erubi (1.7.1)
erubis (2.7.0)
etc (default: 1.0.0)
eventmachine (1.2.7)
execjs (2.7.0)
factory_bot (4.11.1)
factory_bot_rails (4.11.1)
faker (1.9.1)
faraday (0.15.3, 0.14.0)
fcntl (default: 1.0.0)
ffi (1.9.25, 1.9.23)
fiddle (default: 1.0.0)
figaro (1.1.1)
fileutils (default: 1.0.2)
font-awesome-sass (5.2.0, 5.0.9)
gdbm (default: 2.0.0)
globalid (0.4.1)
god (0.13.7)
gon (5.2.3)
grape (1.1.0)
grape-entity (0.7.1)
grape-swagger (0.31.1, 0.30.1)
grape-swagger-entity (0.3.0, 0.2.5)
grape-swagger-ui (2.2.8)
grape_logging (1.8.0)
grape_on_rails_routes (0.3.2)
grape_strip (1.0.0)
hashdiff (0.3.7)
hashie (3.5.7)
http_accept_language (2.1.1)
http_parser.rb (0.6.0)
i18n (1.1.1, 1.0.0, 0.9.5)
i18n_data (0.8.0)
ice_nine (0.11.2)
io-console (default: 0.4.6)
ipaddr (default: 1.2.0)
jaro_winkler (1.5.1)
jbuilder (2.7.0)
jquery-rails (4.3.3, 4.3.1)
json (default: 2.1.0)
jwt (2.1.0)
jwt-multisig (1.0.0)
kaminari (1.1.1)
kaminari-actionview (1.1.1)
kaminari-activerecord (1.1.1)
kaminari-core (1.1.1)
libv8 (6.7.288.46.1 x86_64-linux, 6.3.292.48.1 x86_64-linux)
listen (3.1.5)
loofah (2.2.3, 2.2.2)
mail (2.7.1, 2.7.0)
marcel (0.3.3)
memoist (0.16.0)
metaclass (0.0.4)
method-not-implemented (1.0.1)
method_source (0.9.2, 0.9.0)
mime-types (3.2.2)
mime-types-data (3.2018.0812)
mimemagic (0.3.2)
mini_mime (1.0.1, 1.0.0)
mini_portile2 (2.3.0)
mini_racer (0.2.4, 0.2.3, 0.1.15)
minitest (5.11.3, 5.10.3)
mocha (1.7.0)
momentjs-rails (2.20.1)
money (6.13.1)
msgpack (1.2.4)
multi_json (1.13.1)
multi_xml (0.6.0)
multipart-post (2.0.0)
mustermann (1.0.3)
mustermann-grape (1.0.0)
mysql2 (0.5.2, 0.4.10)
net-telnet (0.1.1)
nio4r (2.3.1, 2.3.0)
nokogiri (1.8.5, 1.8.2)
omniauth (1.8.1)
omniauth-auth0 (2.0.0)
omniauth-barong (0.1.4)
omniauth-google-oauth2 (0.5.3)
omniauth-oauth2 (1.5.0)
openssl (default: 2.1.2)
parallel (1.12.1)
parser (2.5.3.0)
passgen (1.0.2)
peatio (0.4.4)
phonelib (0.6.27)
popper_js (1.14.3)
power_assert (1.1.1)
powerpack (0.1.2)
pry (0.12.2, 0.11.3)
pry-byebug (3.6.0)
pry-rails (0.3.7)
psych (default: 3.0.2)
public_suffix (3.0.3)
puma (3.12.0, 3.11.4, 3.11.3)
quiet_assets (1.1.0)
rack (2.0.6, 2.0.5, 1.6.11)
rack-accept (0.4.5)
rack-attack (5.4.1)
rack-test (1.1.0, 1.0.0, 0.6.3)
rack_session_access (0.2.0)
rails (5.2.1, 5.1.6, 4.2.10)
rails-controller-testing (1.0.2)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (2.0.3, 1.0.9)
rails-html-sanitizer (1.0.4)
rails-i18n (4.0.9)
railties (5.2.1, 5.1.6, 4.2.10)
rainbow (3.0.0)
rake (12.3.1, 12.3.0)
rb-fsevent (0.10.3)
rb-inotify (0.9.10)
rbtree (0.4.2)
rdoc (default: 6.0.1)
recaptcha (4.13.0)
redis (4.0.2)
redis-actionpack (5.0.2)
redis-activesupport (5.0.7)
redis-rack (2.0.4)
redis-rails (5.0.2)
redis-store (1.6.0)
regexp_parser (1.3.0)
request_store (1.4.1)
rspec-core (3.8.0)
rspec-expectations (3.8.2)
rspec-mocks (3.8.0)
rspec-rails (3.8.1)
rspec-retry (0.6.1)
rspec-support (3.8.0)
rubocop (0.60.0)
rubocop-rspec (1.30.0)
ruby-prof (0.17.0)
ruby-progressbar (1.10.0)
ruby_dep (1.5.0)
rubygems-update (2.7.8)
rubytree (1.0.0)
safe_yaml (1.0.4)
sass (3.6.0, 3.5.6)
sass-listen (4.0.0)
sass-rails (5.0.7)
sassc (1.12.1)
sassc-rails (1.3.0)
scanf (default: 1.0.0)
scout_apm (2.4.20)
sdbm (default: 1.0.0)
sentry-raven (2.7.4)
shoulda-matchers (4.0.0.rc1)
sixarm_ruby_unaccent (1.2.0)
spring (2.0.2)
spring-watcher-listen (2.0.1)
sprockets (3.7.2)
sprockets-rails (3.2.1)
stringio (default: 0.0.1)
strong_password (0.0.6)
strscan (default: 1.0.0)
structured_warnings (0.3.0)
test-unit (3.2.7)
thor (0.20.3, 0.20.0)
thread_safe (0.3.6)
tilt (2.0.8)
timecop (0.9.1)
twilio-ruby (5.6.4)
tzinfo (1.2.5)
uglifier (4.1.19, 4.1.8)
unicode-display_width (1.4.0)
unicode_utils (1.4.0)
uniform_notifier (1.11.0)
validate_url (1.0.2)
validates_lengths_from_database (0.7.0)
vault (0.12.0)
virtus (1.0.5)
web-console (3.7.0)
webmock (3.4.2)
webrick (default: 1.4.2)
websocket-driver (0.7.0, 0.6.5)
websocket-extensions (0.1.3)
xmlrpc (0.3.0)
xpath (3.2.0)
zlib (default: 1.0.0)
```

I am not sure what cause the Redis::CommandError (NOAUTH Authentication required.) because I have set the application.yml.

Thanks

**Comment by ysv** [comment]
@dragon28 Probably you set up Redis with password so you need to update application.yml

Try to connect to Redis using redis-cli

**Comment by dragon28** [comment]
> @dragon28 Probably you set up Redis with password so you need to update application.yml
> 
> Try to connect to Redis using redis-cli

@ysv  I have no issue connecting and authenticate with Redis by using the same password which I have set earlier on the **/etc/redis/redis.conf** at the **requirepass** section through redis-cli.

on the other hand, I am getting the Redis::CommandError (NOAUTH Authentication required.) even-though,  I am using the same password which I have set earlier on the **/etc/redis/redis.conf** at the **requirepass** section and **~/peatio/config/application.yml** at the **REDIS_PASSWORD:**  section.

**Comment by ysv** [comment]
@dragon28 yes I see the issue. Already submitted pr. Thanks for issue
