### ISSUE TITLE
Ripple Wallet Client - Transaction signing not supported 

### ISSUE THREAD

**Issue by nikharR** [openware/peatio#1865]
Signing through rpc is deprecated.

Should update Peatio to sign transaction offline.
```
#<WalletClient::Error: "notSupported">
/home/app/lib/wallet_client/rippled.rb:155:in `block (4 levels) in json_rpc'
/home/app/lib/wallet_client/rippled.rb:154:in `tap'
/home/app/lib/wallet_client/rippled.rb:154:in `block (3 levels) in json_rpc'
/home/app/lib/wallet_client/rippled.rb:153:in `tap'
/home/app/lib/wallet_client/rippled.rb:153:in `block (2 levels) in json_rpc'
/home/app/lib/wallet_client/rippled.rb:152:in `yield_self'
/home/app/lib/wallet_client/rippled.rb:152:in `block in json_rpc'
/home/app/lib/wallet_client/rippled.rb:151:in `yield_self'
/home/app/lib/wallet_client/rippled.rb:151:in `json_rpc'
/home/app/lib/wallet_client/rippled.rb:99:in `sign_transaction'
/home/app/lib/wallet_client/rippled.rb:61:in `create_withdrawal!'
/home/app/app/services/wallet_service/rippled.rb:17:in `collect_deposit!'
/home/app/app/workers/worker/deposit_collection.rb:27:in `block in process'
```

**Comment by ysv** [comment]
@nikharR Thanks for your issue! Could you share details please
What is the version of Ripple node ? And which API you enabled ?

**Comment by nikharR** [comment]
@ysv im using the testnet https://s.altnet.rippletest.net:51234. Please see this pull request for more details as to why this isnt considered safe practice :https://github.com/ripple/rippled/pull/2657
