### ISSUE TITLE
Faraday, NGINX, Bad Gateway, Something went wrong, Markets Controller 

### ISSUE THREAD

**Issue by not-a-dev0** [openware/peatio#1943]
Started GET "/trading/usdbtc" for 81.X.9.273 at 2018-12-28 19:23
![screen shot 2018-12-28 at 1 26 13 pm](https://user-images.githubusercontent.com/46028023/50525972-95768e80-0aa4-11e9-97f2-e5a04085c5a0.png)
:04 +0000
Processing by MarketsController#show as HTML
  Parameters: {"market_id"=>"usdbtc"}
Completed 500 Internal Server Error in 23ms

Faraday::Error (-- HTTP 502 Bad Gateway --

-- Request URL --
GET http://sub.domain.io/markets/usdbtc.json

-- Request headers --
{"User-Agent":"Faraday v0.14.0","Cookie":"__cfduid=d2f54a907d4238c268153c3a8b8097fed1540453623; _ga=GA1.2.742752124.1540453624; lc_sso10167037=1544300022699; market_id=usdbtc"}

-- Request body --

-- Response headers --
{"server":"nginx/1.15.7","date":"Fri, 28 Dec 2018 19:23:04 GMT","content-type":"text/html","content-length":"157","connection":"close"}

-- Response body --
<html >
< head><title>502 Bad Gateway</title></head>
<body > 
<center >< h1 > 502 Bad Gateway< /h1 > </ce nter>
<hr><center>nginx/1.15.7</center>
</body>
</html>

):

config/initializers/faraday.rb:22:in `assert_success!'
app/controllers/markets_controller.rb:13:in `show'

**Comment by not-a-dev0** [comment]
I am still trying to setup the trading UI and this is the error I keep getting. :(
