### ISSUE TITLE
Cant Send Collected Fee

### ISSUE THREAD

**Issue by endofthepain** [openware/peatio#2089]
I am using parity for erc20 with peatio 2.0.32 then i get error like this

> Failed to collect fee transfer deposit 80. See exception details below.
#<NoMethodError: undefined method `address' for nil:NilClass>
/home/app/app/services/wallet_service/ethereum.rb:53:in `deposit_collection_fees'
/home/app/app/workers/worker/deposit_collection_fees.rb:27:in `block in process'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/locking/pessimistic.rb:72:in `block in with_lock'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/transactions.rb:220:in `transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/transactions.rb:277:in `transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/locking/pessimistic.rb:70:in `with_lock'
/home/app/app/workers/worker/deposit_collection_fees.rb:15:in `process'
lib/daemons/amqp_daemon.rb:60:in `call'
lib/daemons/amqp_daemon.rb:60:in `block (2 levels) in <main>'
/opt/vendor/bundle/ruby/2.5.0/gems/bunny-2.11.0/lib/bunny/consumer.rb:56:in `call'
/opt/vendor/bundle/ruby/2.5.0/gems/bunny-2.11.0/lib/bunny/channel.rb:1728:in `block in handle_frameset'
/opt/vendor/bundle/ruby/2.5.0/gems/bunny-2.11.0/lib/bunny/consumer_work_pool.rb:107:in `block (2 levels) in run_loop'
/opt/vendor/bundle/ruby/2.5.0/gems/bunny-2.11.0/lib/bunny/consumer_work_pool.rb:102:in `loop'
/opt/vendor/bundle/ruby/2.5.0/gems/bunny-2.11.0/lib/bunny/consumer_work_pool.rb:102:in `block in run_loop'
/opt/vendor/bundle/ruby/2.5.0/gems/bunny-2.11.0/lib/bunny/consumer_work_pool.rb:101:in `catch'
/opt/vendor/bundle/ruby/2.5.0/gems/bunny-2.11.0/lib/bunny/consumer_work_pool.rb:101:in `run_loop'`

**Comment by endofthepain** [comment]
fixed
