### ISSUE TITLE
Cant create deposit_address

### ISSUE THREAD

**Issue by huuhait** [openware/peatio#2211]
Hello when i request get deposit_address but not work :< 
i'm using microkube and blockchain daemons working normal

i tested with curl call to create new address `personal_newAccount` working normal

> Received: {"account_id":1}
  Account Load (0.5ms)  SELECT  `accounts`.* FROM `accounts` WHERE `accounts`.`id` = 1 LIMIT 1
  Currency Load (0.4ms)  SELECT  `currencies`.* FROM `currencies` WHERE `currencies`.`id` = 'eth' LIMIT 1
  Wallet Load (0.5ms)  SELECT  `wallets`.* FROM `wallets` WHERE `wallets`.`status` = 'active' AND `wallets`.`kind` = 100 AND `wallets`.`currency_id` = 'eth' LIMIT 1
  PaymentAddress Load (0.4ms)  SELECT  `payment_addresses`.* FROM `payment_addresses` WHERE `payment_addresses`.`account_id` = 1 ORDER BY `payment_addresses`.`id` DESC LIMIT 1
  Currency Load (0.3ms)  SELECT  `currencies`.* FROM `currencies` WHERE `currencies`.`id` = 'eth' LIMIT 1
  Account Load (0.3ms)  SELECT  `accounts`.* FROM `accounts` WHERE `accounts`.`id` = 1 LIMIT 1
   (0.4ms)  BEGIN
  PaymentAddress Load (0.4ms)  SELECT  `payment_addresses`.* FROM `payment_addresses` WHERE `payment_addresses`.`id` = 1 LIMIT 1 FOR UPDATE
  Member Load (0.5ms)  SELECT  `members`.* FROM `members` WHERE `members`.`id` = 1 LIMIT 1
   (0.4ms)  ROLLBACK
#<Faraday::ConnectionFailed wrapped=#<Net::OpenTimeout: execution expired>>
/usr/local/lib/ruby/2.6.0/net/http.rb:947:in `initialize'
/usr/local/lib/ruby/2.6.0/net/http.rb:947:in `open'
/usr/local/lib/ruby/2.6.0/net/http.rb:947:in `block in connect'
/usr/local/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
/usr/local/lib/ruby/2.6.0/net/http.rb:945:in `connect'
/usr/local/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
/usr/local/lib/ruby/2.6.0/net/http.rb:919:in `start'
/usr/local/lib/ruby/2.6.0/net/http.rb:1470:in `request'
/opt/vendor/bundle/ruby/2.6.0/gems/scout_apm-2.4.24/lib/scout_apm/instruments/net_http.rb:30:in `block in request_with_scout_instruments'
/opt/vendor/bundle/ruby/2.6.0/gems/scout_apm-2.4.24/lib/scout_apm/tracer.rb:34:in `instrument'
/opt/vendor/bundle/ruby/2.6.0/gems/scout_apm-2.4.24/lib/scout_apm/tracer.rb:44:in `instrument'
/opt/vendor/bundle/ruby/2.6.0/gems/scout_apm-2.4.24/lib/scout_apm/instruments/net_http.rb:29:in `request_with_scout_instruments'
/opt/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:87:in `perform_request'
/opt/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:43:in `block in call'
/opt/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
/opt/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/adapter/net_http.rb:38:in `call'
/opt/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/request/url_encoded.rb:15:in `call'
/opt/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
/opt/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
/home/app/config/initializers/faraday.rb:13:in `run_request'
/opt/vendor/bundle/ruby/2.6.0/gems/faraday-0.15.4/lib/faraday/connection.rb:175:in `post'
/home/app/lib/peatio/wallet_client/ethereum.rb:126:in `json_rpc'
/home/app/lib/peatio/wallet_client/ethereum.rb:16:in `block in create_address!'
/home/app/lib/peatio/wallet_client/ethereum.rb:15:in `yield_self'
/home/app/lib/peatio/wallet_client/ethereum.rb:15:in `create_address!'
/home/app/app/services/wallet_service/ethereum.rb:12:in `create_address'
/home/app/app/workers/worker/deposit_coin_address.rb:23:in `block (2 levels) in process'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.0.7.2/lib/active_record/locking/pessimistic.rb:72:in `block in with_lock'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.0.7.2/lib/active_record/transactions.rb:211:in `transaction'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.0.7.2/lib/active_record/transactions.rb:310:in `transaction'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.0.7.2/lib/active_record/locking/pessimistic.rb:70:in `with_lock'
/home/app/app/workers/worker/deposit_coin_address.rb:19:in `block in process'
/home/app/app/workers/worker/deposit_coin_address.rb:18:in `tap'
/home/app/app/workers/worker/deposit_coin_address.rb:18:in `process'
lib/daemons/amqp_daemon.rb:60:in `call'
lib/daemons/amqp_daemon.rb:60:in `block (2 levels) in <main>'
/opt/vendor/bundle/ruby/2.6.0/gems/bunny-2.14.1/lib/bunny/consumer.rb:56:in `call'
/opt/vendor/bundle/ruby/2.6.0/gems/bunny-2.14.1/lib/bunny/channel.rb:1768:in `block in handle_frameset'
/opt/vendor/bundle/ruby/2.6.0/gems/bunny-2.14.1/lib/bunny/consumer_work_pool.rb:108:in `block (2 levels) in run_loop'
/opt/vendor/bundle/ruby/2.6.0/gems/bunny-2.14.1/lib/bunny/consumer_work_pool.rb:103:in `loop'
/opt/vendor/bundle/ruby/2.6.0/gems/bunny-2.14.1/lib/bunny/consumer_work_pool.rb:103:in `block in run_loop'
/opt/vendor/bundle/ruby/2.6.0/gems/bunny-2.14.1/lib/bunny/consumer_work_pool.rb:102:in `catch'
/opt/vendor/bundle/ruby/2.6.0/gems/bunny-2.14.1/lib/bunny/consumer_work_pool.rb:102:in `run_loop'

**Comment by huuhait** [comment]
forgot change geth rpc url on wallet seed :D
