### ISSUE TITLE
Microkube Build Failed Using Latest Docker Image

### ISSUE THREAD

**Issue by knkrth** [openware/peatio#2255]
Hi, Everything works fine without editing the [app.yml](https://github.com/rubykube/microkube/blob/master/config/app.yml) file. 

When I change the value on [app.yml#L9](https://github.com/rubykube/microkube/blob/master/config/app.yml#L9) to `peatio: rubykube/peatio:latest` And run `rake service:all` build fail

Can anyone update the [microkube ](https://github.com/rubykube/microkube) to support the latest peatio version?

**Comment by HafeezRai** [comment]
can you share errors screen shot

**Comment by knkrth** [comment]
With the following images

```
images:
  peatio: rubykube/peatio:latest
  barong: rubykube/barong:latest
  frontend: rubykube/mikroapp:latest
  tower: rubykube/tower:latest
  postmaster: quay.io/openware/postmaster:latest
  arke: rubykube/arke:latest
```
```
instance-1:~/microkube$ rake service:all
Rendering ./terraform/terraform.tfvars
Rendering ./config/barong.env
Rendering ./config/arke/strategy.yaml
Rendering ./config/toolbox.yaml
Rendering ./config/postmaster.env
Rendering ./config/gateway/envoy.json
Rendering ./config/gateway/envoy.yaml
Rendering ./config/frontend/env.js
Rendering ./config/frontend/tower.js
Rendering ./config/peatio.env
Rendering ./config/peatio/management_api_v1.yml
Rendering ./config/peatio/seed/markets.yml
Rendering ./config/peatio/seed/accounts.yml
Rendering ./config/peatio/seed/currencies.yml
Rendering ./config/peatio/seed/blockchains.yml
Rendering ./config/peatio/seed/wallets.yml
Rendering ./config/ranger.env
Rendering ./config/traefik.toml
Rendering ./compose/app.yaml
Rendering ./compose/arke.yaml
Rendering ./compose/daemons.yaml
Rendering ./compose/proxy.yaml
Rendering ./compose/frontend.yaml
Rendering ./compose/backend.yaml
Rendering ./compose/vendor.yaml
Rendering ./compose/gateway.yaml
Rendering ./compose/cryptonodes.yaml
----- Starting the proxy -----
docker-compose up -d proxy
microkube_proxy_1 is up-to-date
----- Starting dependencies -----
docker-compose up -d vault db redis rabbitmq
microkube_vault_1 is up-to-date
microkube_rabbitmq_1 is up-to-date
microkube_redis_1 is up-to-date
microkube_db_1 is up-to-date
docker-compose run --rm vault secrets enable totp \
              && docker-compose run --rm vault secrets disable secret \
              && docker-compose run --rm vault secrets enable -path=secret -version=1 kv \
              || echo Vault already enabled
Error enabling: Error making API request.
URL: POST http://vault:8200/v1/sys/mounts/totp
Code: 400. Errors:
* existing mount at totp/
Vault already enabled
Wait 5 second for backend
----- Running hooks -----
docker-compose run --rm peatio bash -c "./bin/link_config && bundle exec rake db:create db:migrate db:seed"
Link /opt/peatio/config/plugins.yml -> /home/app/config/plugins.yml
Link /opt/peatio/config/seed/accounts.yml -> /home/app/config/seed/accounts.yml
Link /opt/peatio/config/seed/wallets.yml -> /home/app/config/seed/wallets.yml
Link /opt/peatio/config/seed/currencies.yml -> /home/app/config/seed/currencies.yml
Link /opt/peatio/config/seed/markets.yml -> /home/app/config/seed/markets.yml
Link /opt/peatio/config/seed/blockchains.yml -> /home/app/config/seed/blockchains.yml
Link /opt/peatio/config/management_api_v1.yml -> /home/app/config/management_api_v1.yml
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "REDIS_URL". Already set in ENV. (St
ructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "U
RL_HOST". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_ski
pped!' : WARNING: Skipping key "FORCE_SECURE_CONNECTION". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.6.0/gems/figar
o-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "LOG_LEVEL". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/v
endor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "JWT_PUBLIC_KEY". Already set in ENV. (Str
ucturedWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "JW
T_AUDIENCE". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_
skipped!' : WARNING: Skipping key "MINIMUM_MEMBER_LEVEL_FOR_DEPOSIT". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.6.
0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "MINIMUM_MEMBER_LEVEL_FOR_WITHDRAW". Already set in ENV. (Struct
uredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "MINIM
UM_MEMBER_LEVEL_FOR_TRADING". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/applicati
on.rb:88:in `key_skipped!' : WARNING: Skipping key "EVENT_API_JWT_PRIVATE_KEY". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle
/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "EVENT_API_JWT_ALGORITHM". Already set in ENV. (Struct
uredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "EVENT
_API_RABBITMQ_HOST". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:
in `key_skipped!' : WARNING: Skipping key "EVENT_API_RABBITMQ_PORT". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.6.0
/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "EVENT_API_RABBITMQ_USERNAME". Already set in ENV. (StructuredWar
nings::StandardWarning)/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "EVENT_API_RA
BBITMQ_PASSWORD". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in 
`key_skipped!' : WARNING: Skipping key "RANGER_HOST". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.
1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "RANGER_PORT". Already set in ENV. (StructuredWarnings::StandardWarning)/opt/ven
dor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "VAULT_URL". Already set in ENV. (Structured
Warnings::StandardWarning)/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "VAULT_TOK
EN". Already set in ENV. (StructuredWarnings::StandardWarning){"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[35m (0.9ms)\u001b[
0m  \u001b[1m\u001b[35mSET NAMES utf8 COLLATE utf8_general_ci,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZE
RO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[35m (0.9ms)\u001b[0m  \u001b[1m\u001b[35mCREATE DATABASE `peatio_production` DEF
AULT COLLATE `utf8_general_ci`\u001b[0m"}
Database 'peatio_production' already exists
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[35m (0.5ms)\u001b[0m  \u001b[1m\u001b[35mSET NAMES utf8 COLLATE utf8_general_ci,
  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout 
= 2147483\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[35m (0.3ms)\u001b[0m  \u001b[1m\u001b[34mSELECT GET_LOCK('8225823727547923245', 
0)\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[35m (0.6ms)\u001b[0m  \u001b[1m\u001b[34mSELECT `schema_migrations`.`version` FR
OM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[36mActiveRecord::InternalMetadata Load (0.7ms)\u001b[0m  \u001b[1m\u001b[34mSELE
CT  `ar_internal_metadata`.* FROM `ar_internal_metadata` WHERE `ar_internal_metadata`.`key` = 'environment' LIMIT 1\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[35m (0.4ms)\u001b[0m  \u001b[1m\u001b[35mBEGIN\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[35m (0.4ms)\u001b[0m  \u001b[1m\u001b[35mCOMMIT\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[35m (0.5ms)\u001b[0m  \u001b[1m\u001b[34mSELECT RELEASE_LOCK('822582372754792324
5')\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[35m (0.4ms)\u001b[0m  \u001b[1m\u001b[34mSELECT `schema_migrations`.`version` FR
OM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[35m (0.4ms)\u001b[0m  \u001b[1m\u001b[35mBEGIN\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[36mOperations::Account Exists (0.7ms)\u001b[0m  \u001b[1m\u001b[34mSELECT  1 AS 
one FROM `operations_accounts` WHERE `operations_accounts`.`code` = 101 LIMIT 1\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[36mOperations::Account Exists (0.5ms)\u001b[0m  \u001b[1m\u001b[34mSELECT  1 AS 
one FROM `operations_accounts` WHERE `operations_accounts`.`code` = 102 LIMIT 1\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[36mOperations::Account Exists (0.5ms)\u001b[0m  \u001b[1m\u001b[34mSELECT  1 AS 
one FROM `operations_accounts` WHERE `operations_accounts`.`code` = 201 LIMIT 1\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[36mOperations::Account Exists (0.5ms)\u001b[0m  \u001b[1m\u001b[34mSELECT  1 AS 
one FROM `operations_accounts` WHERE `operations_accounts`.`code` = 202 LIMIT 1\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[36mOperations::Account Exists (0.5ms)\u001b[0m  \u001b[1m\u001b[34mSELECT  1 AS 
one FROM `operations_accounts` WHERE `operations_accounts`.`code` = 211 LIMIT 1\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[36mOperations::Account Exists (0.5ms)\u001b[0m  \u001b[1m\u001b[34mSELECT  1 AS 
one FROM `operations_accounts` WHERE `operations_accounts`.`code` = 212 LIMIT 1\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[36mOperations::Account Exists (0.6ms)\u001b[0m  \u001b[1m\u001b[34mSELECT  1 AS 
one FROM `operations_accounts` WHERE `operations_accounts`.`code` = 301 LIMIT 1\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[36mOperations::Account Exists (0.6ms)\u001b[0m  \u001b[1m\u001b[34mSELECT  1 AS 
one FROM `operations_accounts` WHERE `operations_accounts`.`code` = 302 LIMIT 1\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[36mOperations::Account Exists (0.6ms)\u001b[0m  \u001b[1m\u001b[34mSELECT  1 AS 
one FROM `operations_accounts` WHERE `operations_accounts`.`code` = 401 LIMIT 1\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[36mOperations::Account Exists (0.6ms)\u001b[0m  \u001b[1m\u001b[34mSELECT  1 AS 
one FROM `operations_accounts` WHERE `operations_accounts`.`code` = 402 LIMIT 1\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[35m (0.4ms)\u001b[0m  \u001b[1m\u001b[35mCOMMIT\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[35m (0.4ms)\u001b[0m  \u001b[1m\u001b[35mBEGIN\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[36mBlockchain Exists (0.6ms)\u001b[0m  \u001b[1m\u001b[34mSELECT  1 AS one FROM 
`blockchains` WHERE `blockchains`.`key` = 'eth-rinkeby' LIMIT 1\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[36mBlockchain Exists (0.5ms)\u001b[0m  \u001b[1m\u001b[34mSELECT  1 AS one FROM 
`blockchains` WHERE `blockchains`.`key` = 'eth-mainet' LIMIT 1\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[35m (0.3ms)\u001b[0m  \u001b[1m\u001b[35mCOMMIT\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[35m (0.3ms)\u001b[0m  \u001b[1m\u001b[35mBEGIN\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[36mCurrency Exists (0.6ms)\u001b[0m  \u001b[1m\u001b[34mSELECT  1 AS one FROM `c
urrencies` WHERE `currencies`.`id` = 'usd' LIMIT 1\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[36mCurrency Exists (0.5ms)\u001b[0m  \u001b[1m\u001b[34mSELECT  1 AS one FROM `c
urrencies` WHERE `currencies`.`id` = 'eth' LIMIT 1\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[36mCurrency Exists (0.6ms)\u001b[0m  \u001b[1m\u001b[34mSELECT  1 AS one FROM `c
urrencies` WHERE `currencies`.`id` = 'trst' LIMIT 1\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[36mCurrency Exists (0.6ms)\u001b[0m  \u001b[1m\u001b[34mSELECT  1 AS one FROM `c
urrencies` WHERE `currencies`.`id` = 'kyn' LIMIT 1\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[35m (0.3ms)\u001b[0m  \u001b[1m\u001b[35mCOMMIT\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[35m (0.4ms)\u001b[0m  \u001b[1m\u001b[35mBEGIN\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[36mMarket Exists (0.7ms)\u001b[0m  \u001b[1m\u001b[34mSELECT  1 AS one FROM `mar
kets` WHERE `markets`.`id` = 'ethusd' LIMIT 1\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[36mMarket Exists (0.6ms)\u001b[0m  \u001b[1m\u001b[34mSELECT  1 AS one FROM `mar
kets` WHERE `markets`.`id` = 'trsteth' LIMIT 1\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[36mMarket Exists (0.6ms)\u001b[0m  \u001b[1m\u001b[34mSELECT  1 AS one FROM `mar
kets` WHERE `markets`.`id` = 'kyneth' LIMIT 1\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[35m (0.3ms)\u001b[0m  \u001b[1m\u001b[35mCOMMIT\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[35m (0.4ms)\u001b[0m  \u001b[1m\u001b[35mBEGIN\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[36mWallet Exists (0.6ms)\u001b[0m  \u001b[1m\u001b[34mSELECT  1 AS one FROM `wal
lets` WHERE `wallets`.`name` = 'Ethereum Deposit Wallet' LIMIT 1\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[36mCurrency Load (0.7ms)\u001b[0m  \u001b[1m\u001b[34mSELECT  `currencies`.* FRO
M `currencies` WHERE `currencies`.`id` = 'eth' LIMIT 1\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[36mBlockchain Load (0.9ms)\u001b[0m  \u001b[1m\u001b[34mSELECT  `blockchains`.* 
FROM `blockchains` WHERE `blockchains`.`key` = 'eth-rinkeby' LIMIT 1\u001b[0m"}
{"level":"DEBUG","time":"2019-07-10 17:21:53","message":"  \u001b[1m\u001b[35m (0.4ms)\u001b[0m  \u001b[1m\u001b[31mROLLBACK\u001b[0m"}
rake aborted!
Peatio::AdapterRegistry::NotRegisteredAdapterError: ethereum
/opt/vendor/bundle/ruby/2.6.0/gems/peatio-0.6.1/lib/peatio/adapter_registry.rb:14:in `block in []'
/opt/vendor/bundle/ruby/2.6.0/gems/peatio-0.6.1/lib/peatio/adapter_registry.rb:14:in `fetch'
/opt/vendor/bundle/ruby/2.6.0/gems/peatio-0.6.1/lib/peatio/adapter_registry.rb:14:in `[]'
/home/app/app/services/blockchain_service.rb:10:in `initialize'
/home/app/app/models/blockchain.rb:34:in `new'
/home/app/app/models/blockchain.rb:34:in `blockchain_api'
/home/app/app/models/currency.rb:59:in `blockchain_api'
/home/app/app/models/concerns/belongs_to_currency.rb:19:in `blockchain_api'
/home/app/app/models/wallet.rb:48:in `block in <class:Wallet>'
/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:426:in `instance_exec'
/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:605:in `catch'
/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:199:in `block in halting'
/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:513:in `each'
/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:513:in `invoke_before'
/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:131:in `run_callbacks'
/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:816:in `_run_validation_callbacks'
/opt/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.3/lib/active_model/validations/callbacks.rb:118:in `run_validations!'
/opt/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.3/lib/active_model/validations.rb:339:in `valid?'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/validations.rb:67:in `valid?'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/validations.rb:84:in `perform_validations'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/validations.rb:52:in `save!'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:315:in `block in save!'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:265:in `transaction'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:212:in `transaction'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:315:in `save!'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/suppressor.rb:48:in `save!'
/opt/vendor/bundle/ruby/2.6.0/gems/scout_apm-2.4.21/lib/scout_apm/instruments/active_record.rb:378:in `save!'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/persistence.rb:53:in `create!'
/home/app/lib/tasks/seed.rake:73:in `block (4 levels) in <main>'
/home/app/lib/tasks/seed.rake:71:in `each'
/home/app/lib/tasks/seed.rake:71:in `block (3 levels) in <main>'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction
'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:212:in `transaction'
/home/app/lib/tasks/seed.rake:70:in `block (2 levels) in <main>'
/home/app/db/seeds.rb:9:in `<main>'
/opt/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/opt/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `block in load'
/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'
/opt/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:551:in `block in load_seed'
/opt/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:666:in `with_inline_jobs'
/opt/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:551:in `load_seed'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/tasks/database_tasks.rb:281:in `load_seed'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/railties/databases.rake:194:in `block (2 levels) in <main>'
/opt/vendor/bundle/ruby/2.6.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => seed:wallets
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [docker-compose run --rm peatio bash -c "./...]
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/file_utils.rb:67:in `block in create_shell_runner'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/file_utils.rb:57:in `sh'
lib/tasks/service.rake:119:in `start'
lib/tasks/service.rake:7:in `call'
lib/tasks/service.rake:7:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:126:in `block (2 levels) in <top (required)>'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/home/gsrwallet/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
lib/tasks/service.rake:206:in `start'
lib/tasks/service.rake:7:in `call'
lib/tasks/service.rake:7:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:223:in `block (2 levels) in <top (required)>'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/home/gsrwallet/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/bin/rake:23:in `load'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/bin/rake:23:in `<main>'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
/home/gsrwallet/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => service:setup
instance-1:~/microkube$
```

**Comment by HafeezRai** [comment]
this is problem with blockchain.yml file it is related to blockchain data

**Comment by knkrth** [comment]
How to solve it?

**Comment by evan-labs** [comment]
- key:               eth-rinkeby
  name:              Ethereum Rinkeby
  client:            ethereum               # API client name.
  server:            http://geth:8545       # Public Ethereum node endpoint. IMPORTANT: full syncmode.
  height:            2500000                # Initial block number from which sync will be started.
  step: 6               
  explorer_address:         https://rinkeby.etherscan.io/address/#{address}
  explorer_transaction:     https://rinkeby.etherscan.io/tx/#{txid}
  min_confirmations: 6
  status:            active


- key:               eth-mainet
  name:              Ethereum Mainet
  client:            ethereum               # API client name.
  server:            http://geth:8545       # Public Ethereum node endpoint. IMPORTANT: full syncmode.
  height:            5000000                # Initial block number from which sync will be started.
  step: 6                      # Minimal confirmations needed for withdraw and deposit confirmation.
  explorer_address:         https://etherscan.io/address/#{address}
  explorer_transaction:     https://etherscan.io/tx/#{txid}
  min_confirmations: 6
  status:            disabled

**Comment by knkrth** [comment]
Everything working using https://github.com/bjay27/microkube
