### ISSUE TITLE
ETH deposit processing: undefined method `dig' for nil:NilClass

### ISSUE THREAD

**Issue by SimonVillage** [openware/peatio#2539]
I installed the latest version of opendax on an ubuntu server and setup another server with geth rinkeby on it.

It produced me a deposit address and blockchain is getting scanned. However after I did a deposit I got this error

```
{"level":"WARN","time":"2020-04-30 16:07:51","message":"Error: undefined method `dig' for nil:NilClass. Sleeping for 10 seconds"}
{"level":"ERROR","time":"2020-04-30 16:08:01","message":"#<NoMethodError: undefined method `dig' for nil:NilClass>"}
{"level":"ERROR","time":"2020-04-30 16:08:01","message":"/home/app/lib/peatio/ethereum/blockchain.rb:189:in `transaction_status'\n/home/app/lib/peatio/ethereum/blockchain.rb:88:in `fetch_transaction'\n/home/app/app/services/blockchain_service.rb:79:in `update_or_create_deposit'\n/home/app/app/services/blockchain_service.rb:41:in `map'\n/home/app/app/services/blockchain_service.rb:41:in `block in process_block'\n/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'\n/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'\n/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'\n/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'\n/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'\n/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/transactions.rb:212:in `transaction'\n/home/app/app/services/blockchain_service.rb:40:in `process_block'\n/home/app/app/workers/daemons/blockchain.rb:35:in `block in process'\n/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/core_ext/range/each.rb:9:in `each'\n/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/core_ext/range/each.rb:9:in `each'\n/home/app/app/workers/daemons/blockchain.rb:31:in `process'\n/home/app/app/workers/daemons/blockchain.rb:9:in `block (2 levels) in run'"}
{"level":"WARN","time":"2020-04-30 16:08:01","message":"Error: undefined method `dig' for nil:NilClass. Sleeping for 10 seconds"}
```
It's that code part
```
    def transaction_status(block_txn)
      if block_txn.dig('status') == SUCCESS
        'success'
      elsif block_txn.dig('status') == FAILED
        'failed'
      else
        'pending'
      end
    end
```

transaction: https://rinkeby.etherscan.io/tx/0x71015d6c71a998216cb24de173ff25e89bce0b8a375b5263d14c3181db7361a3

**Comment by SimonVillage** [comment]
The issue is probably because of running a light node ... I think we can close this as soon someone can confirm it

**Comment by martianatwork** [comment]
Yep you’re correct you need a full node with mining enabled to process ERC20 transactions
