### ISSUE TITLE
Add new coin to peatio (plugible coin)

### ISSUE THREAD

**Issue by sergzuko** [openware/peatio#2609]
doin all as described in: https://github.com/openware/peatio/blob/master/docs/coins/development.md

Go error with example https://github.com/rubukybe/peatio-litecoin

#<Thread:0x00005635c7c63038@/home/app/app/workers/daemons/blockchain.rb:9 run> terminated with exception (report_on_exception is true):
/home/app/app/services/blockchain_service.rb:10:in `initialize': undefined method `new' for #<Peatio::Litecoin::Blockchain:0x00005635c722db18> (NoMethodError)
	from /home/app/app/workers/daemons/blockchain.rb:13:in `new'
	from /home/app/app/workers/daemons/blockchain.rb:13:in `process'
	from /home/app/app/workers/daemons/blockchain.rb:9:in `block (3 levels) in run'

**Comment by sergzuko** [comment]
Problem in 

    Register your plugin blockchain and wallet to make it accessible by Peatio.️ ®

Peatio::Blockchain.registry[:litecoin] = Litecoin::Blockchain.new
Peatio::Wallet.registry[:litecoind] = Litecoin::Wallet.new


should be 

Peatio::Blockchain.registry[:litecoin] = Litecoin::Blockchain
Peatio::Wallet.registry[:litecoind] = Litecoin::Wallet
