### ISSUE TITLE
Dude

### ISSUE THREAD

**Issue by eliudrojas** [openware/peatio#2701]
Somebody could give some advice

open_stream is restarting every 5 seconds, there are not error showing inside logs
What need to check to find the errors?
Thanks in advance

I',using 2.4.19

How can migrate to 2.6 (all components de opendax)?
I'm doing test with development

What components and versions I have update to 2.4.19 -> 2.6.0?

Thx

/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "URL_HOST". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "FORCE_SECURE_CONNECTION". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "LOG_LEVEL". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "JWT_PUBLIC_KEY". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "JWT_AUDIENCE". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "MINIMUM_MEMBER_LEVEL_FOR_DEPOSIT". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "MINIMUM_MEMBER_LEVEL_FOR_WITHDRAW". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "MINIMUM_MEMBER_LEVEL_FOR_TRADING". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "EVENT_API_JWT_PRIVATE_KEY". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "EVENT_API_JWT_ALGORITHM". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "EVENT_API_RABBITMQ_HOST". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "EVENT_API_RABBITMQ_PORT". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "EVENT_API_RABBITMQ_USERNAME". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "EVENT_API_RABBITMQ_PASSWORD". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "RANGER_HOST". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "RANGER_PORT". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "VAULT_URL". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "VAULT_TOKEN". Already set in ENV. (StructuredWarnings::StandardWarning)
/home/app/lib/peatio/password_generator.rb:14:in `<module:PasswordGenerator>': already initialized constant PasswordGenerator::CHARS (StructuredWarnings::BuiltInWarning)
/home/app/lib/peatio/password_generator.rb:14:in `<module:PasswordGenerator>': previous definition of CHARS was here (StructuredWarnings::BuiltInWarning)

**Comment by huuhait** [comment]
it's just warning
not matter
