### ISSUE TITLE
<NoMethodError: undefined method `[]' for nil:NilClass>

### ISSUE THREAD

**Issue by whatnowangga** [openware/peatio#3042]
Hi
how do i fix the error come from 
```
{"level":"ERROR","time":"2022-04-29 14:31:53","message":"Failed to collect deposit 13. See exception details below."}
{"level":"ERROR","time":"2022-04-29 14:31:53","message":"#<NoMethodError: undefined method `[]' for nil:NilClass>"}
{"level":"ERROR","time":"2022-04-29 14:31:53","message":"
/home/app/app/services/wallet_service.rb:139:in `skip_deposit_collection?'\n
/home/app/app/services/wallet_service.rb:42:in `block in spread_deposit'\n
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/relation/delegation.rb:71:in `each'\n
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/relation/delegation.rb:71:in `each'\n
/home/app/app/services/wallet_service.rb:34:in `map'\n
/home/app/app/services/wallet_service.rb:34:in `spread_deposit'\n
/home/app/app/models/deposit.rb:145:in `spread_between_wallets!'\n
/home/app/app/workers/daemons/deposit.rb:48:in `process_deposit'\n
/home/app/app/workers/daemons/deposit.rb:35:in `block in process'\n
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/relation/delegation.rb:71:in `each'\n
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/relation/delegation.rb:71:in `each'\n
/home/app/app/workers/daemons/deposit.rb:10:in `process'\n
/home/app/app/workers/daemons/base.rb:25:in `run'\nlib/daemons/daemons.rb:21:in `<main>'"}
```

im using peatio 2.6.48

**Comment by behnammby** [comment]
Hi
Recofigure your wallet, I mean from tower, do verify that secrets and other settings is specified. This happens when some settings in wallet configuration is missing.
