### ISSUE TITLE
Docker peatio-specs not coming up

### ISSUE THREAD

**Issue by felipecaldas** [openware/peatio#389]
Hi guys,

Trying to bring up peation workbench on Windows 10 and getting this error:

```
PS D:\Projetos\docker\peatio-workbench> docker-compose up peatio_specs
Starting peatioworkbench_rabbitmq_1 ...
Starting peatioworkbench_redis_1 ...
Starting peatioworkbench_db_1 ... done
Starting peatioworkbench_peatio_specs_1 ... done
Attaching to peatioworkbench_peatio_specs_1
peatio_specs_1    | + bundle exec rspec --exclude-pattern=spec/features/**/*_spec.rb
peatio_specs_1    | /opt/vendor/bundle/ruby/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!' : WARNING: Skipping key "ADMIN". Already set in ENV. (StructuredWarnings::StandardWarning)bundler: failed to load command: rspec (/opt/vendor/bundle/ruby/2.5.0/bin/rspec)
peatio_specs_1    | ActiveRecord::NoDatabaseError: Unknown database 'peatio_test'
peatio_specs_1    |   /opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:23:in `rescue in mysql2_connection'
peatio_specs_1    |   /opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:9:in `mysql2_connection'
peatio_specs_1    |   /opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
peatio_specs_1    |   /opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
peatio_specs_1    |   /opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
peatio_specs_1    |   /opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
peatio_specs_1    |   /usr/local/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
peatio_specs_1    |   /opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
peatio_specs_1    |   /opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
peatio_specs_1    |   /usr/local/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
peatio_specs_1    |   /opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
peatio_specs_1    |   /opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
peatio_specs_1    |   /opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
peatio_specs_1    |   /opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_handling.rb:87:in `connection'
peatio_specs_1    |   /opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:391:in `check_pending!'
peatio_specs_1    |   /home/app/spec/spec_helper.rb:13:in `<top (required)>'
peatio_specs_1    |   /opt/vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration.rb:1455:in `require'
peatio_specs_1    |   /opt/vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration.rb:1455:in `block in requires='
peatio_specs_1    |   /opt/vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration.rb:1455:in `each'
peatio_specs_1    |   /opt/vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration.rb:1455:in `requires='
peatio_specs_1    |   /opt/vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration_options.rb:112:in `block in process_options_into'
peatio_specs_1    |   /opt/vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration_options.rb:111:in `each'
peatio_specs_1    |   /opt/vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration_options.rb:111:in `process_options_into'
peatio_specs_1    |   /opt/vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration_options.rb:21:in `configure'
peatio_specs_1    |   /opt/vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:99:in `setup'
peatio_specs_1    |   /opt/vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:86:in `run'
peatio_specs_1    |   /opt/vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:71:in `run'
peatio_specs_1    |   /opt/vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:45:in `invoke'
peatio_specs_1    |   /opt/vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.0/exe/rspec:4:in `<top (required)>'
peatio_specs_1    |   /opt/vendor/bundle/ruby/2.5.0/bin/rspec:23:in `load'
peatio_specs_1    |   /opt/vendor/bundle/ruby/2.5.0/bin/rspec:23:in `<top (required)>'
peatioworkbench_peatio_specs_1 exited with code 1
PS D:\Projetos\docker\peatio-workbench>
```

As you can see the peatio database is missing, but I thought that the `init_config` command was taking care of it. What am I missing?

Thanks

**Comment by yivo** [comment]
@felipecaldas Hello. You should run `bundle exec rake db:create db:schema:load`. 

When your issue will be resolved pls close the issue. Thanks.

**Comment by felipecaldas** [comment]
Hi @yivo thanks for your assistance. At which moment should I run this command? Should I bring peatio_specs only up and run it?

**Comment by yivo** [comment]
@felipecaldas I recommend you reading Makefile at peatio-workbench so you will understand all the steps.

https://github.com/rubykube/peatio-workbench/blob/master/Makefile

**Comment by felipecaldas** [comment]
Hi @yivo, thanks again. I actually read the Makefile, but I honestly don't know how to run it! I am windows, I suppose "make" is for *nix only?

**Comment by felipecaldas** [comment]
@yivo, ignore me. I understand what you mean now. Thank you!
