### ISSUE TITLE
Sprockets::FileNotFound in Welcome#index 

### ISSUE THREAD

**Issue by eVanilla** [openware/peatio#392]
i did everything that were in setup document and everything's fine but when i load the page `localhost:3000`(running on development mode) and got this error

```
couldn't find file 'yarn_components/raven-js/dist/raven' with type 'application/javascript'
Checked in these paths: 
  /home/....
=======
-- | --
(red) this is the problem ~> 1  //= require yarn_components/raven-js/dist/raven
2  //= require ./lib/sentry 
3  //= require jquery 
4  //= require jquery_ujs 
5  //= require bootstrap
-- | --
```
what should i do now?

**Comment by DanielGorlo** [comment]
Look for 'yarn' rake task in the issues section.

**Comment by eVanilla** [comment]
mhmm.. same as https://github.com/rubykube/peatio/issues/328#issuecomment-359387062
still getting that error

**Comment by shal** [comment]
Hello @eVanilla 

Documentation too old for now, please follow commands in `Dockerfile`.
Hopefully, soon we will update docs.

This command should help you:

```
bundle exec rake tmp:create yarn:install assets:precompile
```

**Comment by eVanilla** [comment]
thnaks for the reply but that command didn't help me:
```
$ bundle exec rake tmp:create yarn:install assets:precompile
/home/evoke/.rvm/gems/ruby-2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. true was converted to "true". (StructuredWarnings::StandardWarning)/home/evoke/.rvm/gems/ruby-2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. true was converted to "true". (StructuredWarnings::StandardWarning)Usage: yarn [options]

yarn: error: no such option: --modules-folder
I, [2018-01-29T12:37:07.160327 #3033]  INFO -- : Writing /home/evoke/Desktop/scripts/peatio/public/assets/font-awesome/fontawesome-webfont-ad6157926c1622ba4e1d03d478f1541368524bfc46f51e42fe0d945f7ef323e4.svg.gz
I, [2018-01-29T12:37:07.171324 #3033]  INFO -- : Writing /home/evoke/Desktop/scripts/peatio/public/assets/market-0f1ba2d856708f21f04cb372ad6874666e9e9ffa19664a02f8f91e7fde131e10.css.gz
I, [2018-01-29T12:37:07.172949 #3033]  INFO -- : Writing /home/evoke/Desktop/scripts/peatio/public/assets/font-awesome/fontawesome-webfont-ad6157926c1622ba4e1d03d478f1541368524bfc46f51e42fe0d945f7ef323e4.svg.gz
rake aborted!
Sprockets::FileNotFound: couldn't find file 'yarn_components/raven-js/dist/raven' with type 'application/javascript'
Checked in these paths: 
  /home/evoke/Desktop/scripts/peatio/app/assets/images
  /home/evoke/Desktop/scripts/peatio/app/assets/javascripts
  /home/evoke/Desktop/scripts/peatio/app/assets/stylesheets
  /home/evoke/Desktop/scripts/peatio/vendor/assets/javascripts
  /home/evoke/Desktop/scripts/peatio/vendor/assets/stylesheets
  /home/evoke/.rvm/gems/ruby-2.5.0/gems/clipboard-rails-1.7.1/vendor/assets/javascripts
  /home/evoke/.rvm/gems/ruby-2.5.0/gems/clipboard-rails-1.7.1/vendor/assets/stylesheets
  /home/evoke/.rvm/gems/ruby-2.5.0/gems/grape-swagger-ui-2.2.8/vendor/assets/fonts
  /home/evoke/.rvm/gems/ruby-2.5.0/gems/grape-swagger-ui-2.2.8/vendor/assets/images
  /home/evoke/.rvm/gems/ruby-2.5.0/gems/grape-swagger-ui-2.2.8/vendor/assets/javascripts
  /home/evoke/.rvm/gems/ruby-2.5.0/gems/grape-swagger-ui-2.2.8/vendor/assets/stylesheets
  /home/evoke/.rvm/gems/ruby-2.5.0/gems/momentjs-rails-2.17.1/vendor/assets/javascripts
  /home/evoke/.rvm/gems/ruby-2.5.0/gems/bourbon-4.3.4/app/assets/stylesheets
  /home/evoke/.rvm/gems/ruby-2.5.0/gems/angularjs-rails-1.3.15/vendor/assets/javascripts
  /home/evoke/.rvm/gems/ruby-2.5.0/gems/jquery-rails-4.3.1/vendor/assets/javascripts
  /home/evoke/.rvm/gems/ruby-2.5.0/gems/coffee-rails-4.2.2/lib/assets/javascripts
  /home/evoke/.rvm/gems/ruby-2.5.0/gems/datagrid-1.5.7/app/assets/stylesheets
  /home/evoke/.rvm/gems/ruby-2.5.0/gems/bootstrap-sass-3.2.0.2/assets/stylesheets
  /home/evoke/.rvm/gems/ruby-2.5.0/gems/bootstrap-sass-3.2.0.2/assets/javascripts
  /home/evoke/.rvm/gems/ruby-2.5.0/gems/bootstrap-sass-3.2.0.2/assets/fonts
  /home/evoke/.rvm/gems/ruby-2.5.0/gems/bootstrap-sass-3.2.0.2/assets/images
  /home/evoke/.rvm/gems/ruby-2.5.0/gems/font-awesome-sass-4.7.0/assets/stylesheets
  /home/evoke/.rvm/gems/ruby-2.5.0/gems/font-awesome-sass-4.7.0/assets/fonts
/home/evoke/Desktop/scripts/peatio/app/assets/javascripts/admin.js:1
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/resolve.rb:65:in `resolve!'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:399:in `resolve'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:207:in `process_require_directive'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:180:in `block in process_directives'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:178:in `each'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:178:in `process_directives'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:83:in `_call'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:68:in `call'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:23:in `block in call'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/utils.rb:200:in `dfs'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:24:in `call'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:134:in `block in find'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:133:in `each'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:133:in `find'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
/home/evoke/.rvm/gems/ruby-2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/home/evoke/.rvm/gems/ruby-2.5.0@global/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/home/evoke/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `eval'
/home/evoke/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
zlib(finalizer): Zlib::GzipWriter object must be closed explicitly.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): Zlib::GzipWriter object must be closed explicitly.
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): Zlib::GzipWriter object must be closed explicitly.
zlib(finalizer): the stream was freed prematurely.
```

**Comment by eVanilla** [comment]
Well, I think I have to wait for the update

**Comment by shal** [comment]
@eVanilla It seems you have an old version of `yarn`.
Can you try to install the latest version

```
npm install -g yarn
```

**Comment by eVanilla** [comment]
Sorry, I still get the same error

**Comment by yivo** [comment]
@eVanilla Install Yarn & exec `bundle exec rake yarn:install`.

How to install – https://yarnpkg.com/en/docs/install.

**Comment by yivo** [comment]
@eVanilla When issue will be resolved pls close it. Thanks.

**Comment by eVanilla** [comment]
unfortunately i already installed the yarn and now the error has been changed to this:
```
$ rake yarn:install
/usr/bin/env: ‘node’: No such file or directory
```

**Comment by yivo** [comment]
@eVanilla It is related to your node.js installation, not to peatio.

**Comment by eVanilla** [comment]
Let me check it out, now I close this until I receive another error

**Comment by yozef** [comment]
Went through these steps... turned out I had a old version of yarn & precompile:
`npm install -g yarn` then `bundle exec rake tmp:create yarn:install assets:precompile`

The Dockerfile had this missing for me. Thanks guys! I look forward to dig further.
