### ISSUE TITLE
Undefined method balance for CoinAPI::BitGo

### ISSUE THREAD

**Issue by yivo** [openware/peatio#418]
```
/home/app/app/models/currency.rb:65:in `refresh_balance': undefined method `balance' for #<CoinAPI::BitGo:0x000055f8d1cb9948> (NoMethodError)
  from lib/daemons/hot_wallets.rb:9:in `process'
  from lib/daemons/hot_wallets.rb:21:in `block (2 levels) in <main>'
  from lib/daemons/hot_wallets.rb:21:in `each'
  from lib/daemons/hot_wallets.rb:21:in `block in <main>'
  from lib/daemons/hot_wallets.rb:19:in `tap'
  from lib/daemons/hot_wallets.rb:19:in `<main>'
```

Please change `balance` to `load_balance` at app/models/currency.rb

**Comment by yivo** [comment]
Fixed in #419.
