### ISSUE TITLE
Specs are failing due to removed #to_d method from Rails 4.0

### ISSUE THREAD

**Issue by yivo** [openware/peatio#47]
@mod This causes several specs to fail after upgrade to Rails 4.2. We need either update the code either monkey-patch String & BigDecimal prototypes.

```
  9) Matching::LimitOrder initialize should throw invalid order error for empty attributes
     # No reason given
     Failure/Error:
       expect do
         Matching::LimitOrder.new(type: '', price: '', volume: '')
       end.to raise_error(Matching::InvalidOrderError)

       expected Matching::InvalidOrderError, got #<ArgumentError: invalid value for BigDecimal(): ""> with backtrace:
         # ./app/models/matching/limit_order.rb:12:in `initialize'
         # ./spec/models/matching/limit_order_spec.rb:7:in `new'
         # ./spec/models/matching/limit_order_spec.rb:7:in `block (4 levels) in <top (required)>'
         # ./spec/models/matching/limit_order_spec.rb:6:in `block (3 levels) in <top (required)>'
     # ./spec/models/matching/limit_order_spec.rb:6:in `block (3 levels) in <top (required)>'
```

**Comment by yivo** [comment]
@mod Actually this is also because ruby was upgraded to 2.4.x. 

Often peatio executes `"".to_d` which evaluates to `ArgumentError: invalid value for BigDecimal(): ""`
