### ISSUE TITLE
Specs are failing due to missing ID in document

### ISSUE THREAD

**Issue by yivo** [openware/peatio#50]
```
  7) show account info user can cancel his own order
     # No reason given
     Got 0 failures and 2 other errors:

     7.1) Failure/Error: click_link page.all('#my_order_tabs_wrapper li').first.text

          NoMethodError:
            undefined method `text' for nil:NilClass
          # ./spec/features/market_trade_history_spec.rb:24:in `block (3 levels) in <top (required)>'
          # ./spec/features/market_trade_history_spec.rb:23:in `block (2 levels) in <top (required)>'
```

**Comment by yivo** [comment]
@mod Assigned to Yaroslav

**Comment by ysv** [comment]
we have one more failure in this test
````
Mocha::ExpectationError:
       not all expectations were satisfied
       unsatisfied expectations:
       - expected exactly once, not yet invoked: AMQPQueue.enqueue(:matching, {:action => "cancel", :order => {:id => 1246, :market => "btccny", :type => :ask, :ord_type => "limit", :volume => 0.1e1, :price => 0.236e2, :locked => 0.1e1, :timestamp => 1513167031}})
       satisfied expectations:
       - allowed any number of times, invoked 6 times: AMQPQueue.publish(any_parameters)
       - allowed any number of times, not yet invoked: KlineDB.kline(any_parameters)
````

**Comment by ysv** [comment]
@yivo is it my task to fix this one too ?

**Comment by yivo** [comment]
@yssavchuk Does this spec fails in master?

**Comment by ysv** [comment]
@yivo yes

**Comment by yivo** [comment]
@yssavchuk Got it. I will create an issue.
