### ISSUE TITLE
Fix warnings from figaro

### ISSUE THREAD

**Issue by yivo** [openware/peatio#792]

**Comment by yivo** [comment]
```
/Users/yaroslav/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. false was converted to "false". (StructuredWarnings::StandardWarning)/Users/yaroslav/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 180 was converted to "180". (StructuredWarnings::StandardWarning)/Users/yaroslav/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 3000 was converted to "3000". (StructuredWarnings::StandardWarning)/Users/yaroslav/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 80 was converted to "80". (StructuredWarnings::StandardWarning)
```

**Comment by yivo** [comment]
Fixed in #808.
