### ISSUE TITLE
Several specs are failing (seed 63928)

### ISSUE THREAD

**Issue by yivo** [openware/peatio#86]

**Comment by gfedorenko** [comment]
```
Failures:

  1) Sign up allows a user to sign up and activate the account
     Failure/Error: click_on I18n.t('header.signup')
     
     Capybara::ElementNotFound:
       Unable to find visible link or button "Sign Up"
     # /home/galya/.gem/ruby/2.4.0/gems/capybara-2.16.1/lib/capybara/node/finders.rb:314:in `block in synced_resolve'
     # /home/galya/.gem/ruby/2.4.0/gems/capybara-2.16.1/lib/capybara/node/base.rb:85:in `synchronize'
     # /home/galya/.gem/ruby/2.4.0/gems/capybara-2.16.1/lib/capybara/node/finders.rb:302:in `synced_resolve'
     # /home/galya/.gem/ruby/2.4.0/gems/capybara-2.16.1/lib/capybara/node/finders.rb:37:in `find'
     # /home/galya/.gem/ruby/2.4.0/gems/capybara-2.16.1/lib/capybara/node/actions.rb:25:in `click_link_or_button'
     # /home/galya/.gem/ruby/2.4.0/gems/capybara-2.16.1/lib/capybara/session.rb:810:in `block (2 levels) in <class:Session>'
     # /home/galya/.gem/ruby/2.4.0/gems/capybara-2.16.1/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
     # ./spec/features/sign_up_spec.rb:6:in `fill_in_sign_up_form'
     # ./spec/features/sign_up_spec.rb:31:in `block (2 levels) in <top (required)>'

  2) Sign up allows user to resend confirmation email
     Failure/Error: click_on I18n.t('header.signup')
     
     Capybara::ElementNotFound:
       Unable to find visible link or button "Sign Up"
     # /home/galya/.gem/ruby/2.4.0/gems/capybara-2.16.1/lib/capybara/node/finders.rb:314:in `block in synced_resolve'
     # /home/galya/.gem/ruby/2.4.0/gems/capybara-2.16.1/lib/capybara/node/base.rb:85:in `synchronize'
     # /home/galya/.gem/ruby/2.4.0/gems/capybara-2.16.1/lib/capybara/node/finders.rb:302:in `synced_resolve'
     # /home/galya/.gem/ruby/2.4.0/gems/capybara-2.16.1/lib/capybara/node/finders.rb:37:in `find'
     # /home/galya/.gem/ruby/2.4.0/gems/capybara-2.16.1/lib/capybara/node/actions.rb:25:in `click_link_or_button'
     # /home/galya/.gem/ruby/2.4.0/gems/capybara-2.16.1/lib/capybara/session.rb:810:in `block (2 levels) in <class:Session>'
     # /home/galya/.gem/ruby/2.4.0/gems/capybara-2.16.1/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
     # ./spec/features/sign_up_spec.rb:6:in `fill_in_sign_up_form'
     # ./spec/features/sign_up_spec.rb:47:in `block (2 levels) in <top (required)>'

  3) Sign up allows a user to sign up and activate the account in a different browser
     Failure/Error: click_on I18n.t('header.signup')
     
     Capybara::ElementNotFound:
       Unable to find visible link or button "Sign Up"
     # /home/galya/.gem/ruby/2.4.0/gems/capybara-2.16.1/lib/capybara/node/finders.rb:314:in `block in synced_resolve'
     # /home/galya/.gem/ruby/2.4.0/gems/capybara-2.16.1/lib/capybara/node/base.rb:85:in `synchronize'
     # /home/galya/.gem/ruby/2.4.0/gems/capybara-2.16.1/lib/capybara/node/finders.rb:302:in `synced_resolve'
     # /home/galya/.gem/ruby/2.4.0/gems/capybara-2.16.1/lib/capybara/node/finders.rb:37:in `find'
     # /home/galya/.gem/ruby/2.4.0/gems/capybara-2.16.1/lib/capybara/node/actions.rb:25:in `click_link_or_button'
     # /home/galya/.gem/ruby/2.4.0/gems/capybara-2.16.1/lib/capybara/session.rb:810:in `block (2 levels) in <class:Session>'
     # /home/galya/.gem/ruby/2.4.0/gems/capybara-2.16.1/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
     # ./spec/features/sign_up_spec.rb:6:in `fill_in_sign_up_form'
     # ./spec/features/sign_up_spec.rb:37:in `block (2 levels) in <top (required)>'

Finished in 8 minutes 45 seconds (files took 4.79 seconds to load)
581 examples, 3 failures, 10 pending

Failed examples:

rspec ./spec/features/sign_up_spec.rb:30 # Sign up allows a user to sign up and activate the account
rspec ./spec/features/sign_up_spec.rb:46 # Sign up allows user to resend confirmation email
rspec ./spec/features/sign_up_spec.rb:36 # Sign up allows a user to sign up and activate the account in a different browser

Randomized with seed 63928

```

**Comment by yivo** [comment]
Duplicate of #39
